### ISSUE TITLE
FormData TypeError: first argument must be a string or Buffer

### ISSUE THREAD

**Issue by iongion** [bitinn/node-fetch#129]
Using:
- node-fetch **1.5.3**
- form-data **1.0.0-rc4** from https://github.com/form-data

For this:

```
      var body = new FormData();
      body.append('key1', 'val1');
      var options = { url: 'http://my.host/local', body: body };
      fetch(options.url, options)
```

I get an error with the following stack track:

````
TypeError: first argument must be a string or Buffer
      at ClientRequest.OutgoingMessage.write (_http_outgoing.js:443:11)
      at FormData.ondata (stream.js:31:26)
      at FormData.CombinedStream.write (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:118:8)
      at FormData.CombinedStream._pipeNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:106:8)
      at FormData.CombinedStream._getNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:79:10)
      at FormData.CombinedStream._pipeNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:107:8)
      at FormData.CombinedStream._getNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:79:10)
      at FormData.CombinedStream._pipeNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:107:8)
      at FormData.<anonymous> (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:91:10)
      at FormData.<anonymous> (W:\MyProject\node_modules\form-data\lib\form_data.js:246:5)
      at FormData.CombinedStream._getNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:84:3)
      at FormData.CombinedStream._pipeNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:107:8)
      at FormData.CombinedStream._getNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:79:10)
      at FormData.CombinedStream._pipeNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:107:8)
      at FormData.CombinedStream._getNext (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:79:10)
      at FormData.CombinedStream.resume (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:134:10)
      at FormData.CombinedStream.pipe (W:\MyProject\node_modules\combined-stream\lib\combined_stream.js:64:8)
      at W:\MyProject\node_modules\node-fetch\index.js:205:17
      at Promise._execute (W:\MyProject\node_modules\bluebird\js\release\debuggability.js:272:9)
      at Promise._resolveFromExecutor (W:\MyProject\node_modules\bluebird\js\release\promise.js:475:18)
      at new Promise (W:\MyProject\node_modules\bluebird\js\release\promise.js:77:14)
      at new Fetch (W:\MyProject\node_modules\node-fetch\index.js:49:9)
      at Fetch (W:\MyProject\node_modules\node-fetch\index.js:37:10)
      at Client.doRequest (W:\MyProject\lib\api\HTTPClient.js:104:12)
      at Object.Dailymotion.performRequest (W:\MyProject\lib\modules\StreamingProvider\support\clients\Dailymotion.js:56:26)
      at Object.Dailymotion.createVideo (W:\MyProject\lib\modules\StreamingProvider\support\clients\Dailymotion.js:74:19)
      at W:\MyProject\lib\modules\StreamingProvider\support\VideoManager.js:61:30
      at tryCatcher (W:\MyProject\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (W:\MyProject\node_modules\bluebird\js\release\promise.js:504:31)
      at Promise._settlePromise (W:\MyProject\node_modules\bluebird\js\release\promise.js:561:18)
      at Promise._settlePromise0 (W:\MyProject\node_modules\bluebird\js\release\promise.js:606:10)
      at Promise._settlePromises (W:\MyProject\node_modules\bluebird\js\release\promise.js:685:18)
      at Async._drainQueue (W:\MyProject\node_modules\bluebird\js\release\async.js:138:16)
      at Async._drainQueues (W:\MyProject\node_modules\bluebird\js\release\async.js:148:10)
      at Immediate.Async.drainQueues [as _onImmediate] (W:\MyProject\node_modules\bluebird\js\release\async.js:17:14)
````

Checked all that I could find at form-data repository, but there is nothing helpful that can help identify the origin of the issue. What can be done ?

**Comment by bitinn** [comment]
http://stackoverflow.com/questions/14835582/nodejs-first-argument-must-be-a-string-or-buffer-when-using-response-write-w

Likely a problem with your server API. You can see the error is coming from node.js core, if you can confirm it's a bug in node.js, then you can open a ticket for them.

**Comment by iongion** [comment]
@bitinn Thank you!
