### ISSUE TITLE
alert/undefined is not an object (evaluating 'this._highlightSlides.getSlider')

### ISSUE THREAD

**Issue by dsuket** [bitinn/node-fetch#160]
3件ほど出てる

```
name: techfeed
hostname: app-techfeed
pid: 22504
time: Fri Sep 09 2016 08:42:27 GMT+0900 (JST)
level: ERROR
category: techfeed:app:clientlog
msg: Caught exception TfExceptionHandler


clientlog: {
  "level": 50,
  "localTime": "2016-09-08T23:42:24.719Z",
  "url": "file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/index.html",
  "user": {
    "id": "57a1e8ef3c7132f8099a26f8",
    "username": "kanausaromeo"
  },
  "data": {}
}
req.url: /api/clientLogs/log
req.headers: {
  "host": "techfeed.io",
  "accept": "application/json",
  "accept-encoding": "gzip, deflate",
  "accept-language": "ja-jp",
  "content-type": "application/json",
  "origin": "null",
  "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36",
  "x-access-token": "PwoDNLBdGU6VNc9uQTCJVErxsUX78Cz9bNZPVLizcQEyCSOXSHMFQNTHzkCUeSHI",
  "x-techfeed-client-type": "ios",
  "x-techfeed-client-version": "3.1.0",
  "x-forwarded-for": "106.128.17.2",
  "x-forwarded-port": "443",
  "x-forwarded-proto": "https",
  "content-length": "3152",
  "connection": "keep-alive"
}
user: {
  "id": "57a1e8ef3c7132f8099a26f8",
  "username": "kanausaromeo",
  "email": "kanausaromeo@gmail.com",
  "emailVerified": true,
  "setupCompleted": true
}


* err.name: TypeError
* err.message: undefined is not an object (evaluating 'this._highlightSlides.getSlider')
* err.code: undefined
* err.signal: undefined
* err.status: undefined
* err.statusCode: undefined
* err.info: undefined


_updateSwiperContainerSize@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/main.js:6323:44
file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/main.js:6210:54
__tryOrUnsub@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8215:21
next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8164:35
_next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8114:31
next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8078:24
_next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:94554:31
next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8078:24
_next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8114:31
next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8078:24
_next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:97809:31
next@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:8078:24
onLoad@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:58521:43
invokeTask@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:147641:44
onInvokeTask@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:12033:52
invokeTask@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:147640:56
runTask@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:147541:59
invoke@file:///var/containers/Bundle/Application/1FBB6D46-E54F-4782-B88A-8AEA56D627F6/TechFeed.app/www/scripts/vendor.js:147708:42
```

**Comment by dsuket** [comment]
同じようなのが出てるけど、これも一緒か？
```
name: techfeed
hostname: app2-techfeed
pid: 29460
time: Fri Sep 09 2016 08:46:12 GMT+0900 (JST)
level: ERROR
category: techfeed:app:clientlog
msg: Caught exception TfExceptionHandler


clientlog: {
  "level": 50,
  "localTime": "2016-09-08T23:46:07.671Z",
  "url": "file:///android_asset/www/index.html",
  "user": {
    "id": "5797906f44f504830b2fb15b",
    "username": "rockster"
  },
  "data": {}
}
req.url: /api/clientLogs/log
req.headers: {
  "host": "techfeed.io",
  "accept": "application/json",
  "accept-encoding": "gzip, deflate",
  "accept-language": "ja-jp",
  "content-type": "application/json",
  "origin": "file://",
  "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MTC20F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Crosswalk/17.46.448.10 Mobile Safari/537.36",
  "x-access-token": "koxuGFOdBGqV8kszXprE1VFzPF8tGkCyiTXhUjCGd2b2QplhT9SgsnoDNBR8dN3U",
  "x-techfeed-client-type": "android",
  "x-techfeed-client-version": "3.1.0",
  "x-forwarded-for": "1.66.105.229",
  "x-forwarded-port": "443",
  "x-forwarded-proto": "https",
  "content-length": "1546",
  "connection": "keep-alive"
}
user: {
  "id": "5797906f44f504830b2fb15b",
  "username": "rockster",
  "email": "ken.tasaki@samurai-project.com",
  "emailVerified": true,
  "setupCompleted": true
}


* err.name: TypeError
* err.message: Cannot read property 'getSlider' of undefined
* err.code: undefined
* err.signal: undefined
* err.status: undefined
* err.statusCode: undefined
* err.info: undefined


TypeError: Cannot read property 'getSlider' of undefined
    at HighlightMultiPage._updateSwiperContainerSize (file:///android_asset/www/scripts/main.js:6323:44)
    at SafeSubscriber._next (file:///android_asset/www/scripts/main.js:6210:28)
    at SafeSubscriber.__tryOrUnsub (file:///android_asset/www/scripts/vendor.js:8215:17)
    at SafeSubscriber.next (file:///android_asset/www/scripts/vendor.js:8164:23)
    at Subscriber._next (file:///android_asset/www/scripts/vendor.js:8114:27)
    at Subscriber.next (file:///android_asset/www/scripts/vendor.js:8078:19)
    at MapSubscriber._next (file:///android_asset/www/scripts/vendor.js:94554:27)
    at MapSubscriber.Subscriber.next (file:///android_asset/www/scripts/vendor.js:8078:19)
    at CatchSubscriber.Subscriber._next (file:///android_asset/www/scripts/vendor.js:8114:27)
    at CatchSubscriber.Subscriber.next (file:///android_asset/www/scripts/vendor.js:8078:19)
```

**Comment by bitinn** [comment]
The whole log doesn't have a single mention of `node-fetch`, I am guessing you posted to the wrong issue tracker.

**Comment by dsuket** [comment]
Wow!
Sorry, I made a mistake
