### ISSUE TITLE
access-control-expose-headers  is not a legal HTTP header name

### ISSUE THREAD

**Issue by makecontact** [bitinn/node-fetch#411]
Fetch keeps throwing this error when hits this particular site in my list. AFAIK, this is a legit header.

TypeError: access-control-expose-headers  is not a legal HTTP header name
    at sanitizeName (/var/www/makecontact.engine/node_modules/node-fetch/lib/index.js:733:9)
    at Headers.has (/var/www/makecontact.engine/node_modules/node-fetch/lib/index.js:883:22)
    at Headers.append (/var/www/makecontact.engine/node_modules/node-fetch/lib/index.js:868:13)
    at ClientRequest.<anonymous> (/var/www/makecontact.engine/node_modules/node-fetch/lib/index.js:1427:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)

```
var fetch = require('node-fetch');

fetch('http://fortunefood.sg').then(function(res) {
	return res.textConverted();
}).then(function(body) {
	console.log('ok');
}).
catch (function(err) {
	console.log(err);
});
```

**Comment by bitinn** [comment]
`curl -I` result

```
HTTP/1.1 301 Moved Permanently
Content-Length: 146
Content-Type: text/html; charset=UTF-8
Location: https://fortunefood.sg/
Server: Microsoft-IIS/10.0
X-Powered-By-Plesk: PleskWin
Access-Control-Expose-Headers : WWW-Authenticate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Headers: accept, authorization, Content-Type
Date: Sat, 03 Mar 2018 03:51:02 GMT
```

see that space in `Access-Control-Expose-Headers :` that shouldn't exist :)

**Comment by TimothyGu** [comment]
Browsers seem to act different. While Firefox just ignores that header, Chrome removes the whitespace. Neither browser exposes this header through `response.headers` however, per rules in the Fetch Standard.

We should probably just filter out any invalid header.

**Comment by makecontact** [comment]
Filtering out this kind of error would be good. 

Fetch is not throwing a FetchError but throwing a TypeError which I can't catch inside Fetch. (without some dodgy external handling).

If I catch the 'TypeError' externally, I'm left with this FetchError - which is easily handled in the final catch.

`{ FetchError: request to https://fortunefood.sg/ failed, reason: Parse Error
    at ClientRequest.<anonymous> (/var/www/makecontact.crawl/node_modules/node-fetch/lib/index.js:1376:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketOnData (_http_client.js:445:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
  message: 'request to https://fortunefood.sg/ failed, reason: Parse Error',
  type: 'system',
  errno: 'HPE_CB_headers_complete',
  code: 'HPE_CB_headers_complete' }`

**Comment by bitinn** [comment]
I don't know the [rfc](https://tools.ietf.org/html/rfc7230#section-3.2) well enough to say if we should normalize header *name* at all; [Fetch Spec](https://fetch.spec.whatwg.org/#concept-header) only explicit tell us to normalize header *value*.

Ignore is a bit annoying as it always results in people asking why a certain header isn't being parsed by the library. I think we should at least log something so people have some obvious output to troubleshoot with.

We will take a PR with tests, the relevant code is here:

https://github.com/bitinn/node-fetch/blob/master/src/headers.js#L10-L24
