### ISSUE TITLE
error: self is not defined after webpack build

### ISSUE THREAD

**Issue by rainmanhhh** [bitinn/node-fetch#534]
```ts
import fetch from 'node-fetch'

// todo data type
export async function callApi(data: ApiRequest) {
  console.log('call api with data:', data)
  const response = await fetch(config.apiUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'x-www-form-urlencoded'
    },
    body: 'data=' + encodeURIComponent(JSON.stringify(data))
  })
  const resp = await (response.json() as Promise<ApiResponse>)
  if (resp.status === Status.Fail) {
    console.error('ApiResponse status is failed:', resp)
    throw new Error('ApiResponse status is failed:' + resp.codeDesc)
  }
  return resp.responseContent
}
```

code above works well with tsc, but after webpack building, it reports:
```
ReferenceError: self is not defined
    at eval (webpack:///./node_modules/node-fetch/browser.js?:3:28)
    at Object../node_modules/node-fetch/browser.js (E:\workspace\wjw\dist\app.js:97:1)
    at __webpack_require__ (E:\workspace\wjw\dist\app.js:20:30)
    at eval (webpack:///./src/api.ts?:43:36)
    at Object../src/api.ts (E:\workspace\wjw\dist\app.js:164:1)
```

node version 10.12
module version:
    "typescript": "^3.1.3",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2"

  "dependencies": {
    "node-fetch": "^2.2.0",

**Comment by jimmywarting** [comment]
why not use `window.fetch` instead of importing node-fetch?

**Comment by rainmanhhh** [comment]
> why not use `window.fetch` instead of importing node-fetch?

it's a server-side app, not running on browser

**Comment by bitinn** [comment]
Hi @rainmanhhh, please checkout #545 and see if it works.
