### ISSUE TITLE
Error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA

### ISSUE THREAD

**Issue by khflx** [bitinn/node-fetch#561]
Hi, I want to upload the readable obtained from a network request as a readable stream to my file server, but doing so will cause an error to be thrown. 

 my upload code: [https://paste.ubuntu.com/p/GBB6vh93w8/](url)

get error message:
`Error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA
      at MultipartParser.end (/home/***/node_modules/formidable/lib/multipart_parser.js:326:12)
      at IncomingMessage.<anonymous> (/home/***/node_modules/formidable/lib/incoming_form.js:132:30)
      at IncomingMessage.emit (events.js:182:13)
      at endReadableNT (_stream_readable.js:1092:12)`

**Comment by khflx** [comment]
How to fix it?
