### ISSUE TITLE
Unhandled promise rejection with size limit and gunzip

### ISSUE THREAD

**Issue by MarcelNebel** [bitinn/node-fetch#593]
I am running the following code
	try {
		fetch(request, reqOptions)
		.then(res => {res.buffer().then(html => {.....}})
		.catch(err => {
			log("transfer", "ERROR RECEIVED", err.core, err.errno, err.message)
with reqOptions containing a size limit.
When I am reading a request from a URL, which supports compression and the decompressed file size exceeds the limit, I get the following error:

(node:24216) UnhandledPromiseRejectionWarning: FetchError: content size at https://sample.page.html over limit: 100000
    at Gunzip.<anonymous> (/home/user/APP/node_modules/node-fetch/lib/index.js:393:12)
    at Gunzip.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Gunzip.Readable.push (_stream_readable.js:219:10)
    at Gunzip.Transform.push (_stream_transform.js:151:32)
    at Zlib.processCallback (zlib.js:590:10)

Unfortunately the .catch block does not catch that error although the manual claims all errors would be catched. 
Am I doing something wrong? I have a tight memory limit on the received file length, hence I require the size option. Is there some other way to catch the error? Timeout errors and 404s are properly catched, though.

**Comment by MarcelNebel** [comment]
Problem solved. Another .catch is required for reading the buffer. This is independent on the fetch .catch.

**Comment by MarcelNebel** [comment]
See above. No issue with the code.
