### ISSUE TITLE
Invariant Violation Issue

### ISSUE THREAD

**Issue by shridharbhande-tudip** [bitinn/node-fetch#609]
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';

const link = createHttpLink({ uri: '/graphql', fetch: fetch });
at new InvariantError (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/node_modules/apollo-link-http-common/node_modules/ts-invariant/lib/invariant.js:16:28)
at Object.exports.checkFetcher (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/node_modules/apollo-link-http-common/lib/index.js:65:15)
at exports.createHttpLink (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/node_modules/apollo-link-http/lib/httpLink.js:9:31)
at Module.1TCz (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/FCCYkOEpZlp1z4k4uL7i_/pages/app.js:1:3209)
at r (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/FCCYkOEpZlp1z4k4uL7i/pages/app.js:1:225)
at Object.0 (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/FCCYkOEpZlp1z4k4uL7i/pages/app.js:1:1804)
at r (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/FCCYkOEpZlp1z4k4uL7i/pages/app.js:1:225)
at /home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/FCCYkOEpZlp1z4k4uL7i/pages/app.js:1:1059
at Object. (/home/lt-113/Documents/ShridharProject/Shopify-FENode/shopify/.next/server/static/FCCYkOEpZlp1z4k4uL7i/pages/_app.js:1:1068)
at Module._compile (module.js:569:30) framesToPop: 1, name: 'Invariant Violation' }
{ Invariant Violation:
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

Why this error is occurring on my local machine?

**Comment by bitinn** [comment]
the error is thrown by apollo, you want to ask them instead.
